### ISSUE TITLE
Failing unit test - test_table_coverage, need more metadata providers

### ISSUE THREAD

**Issue by kristian-94** [jcrodriguez-dis/moodle-mod_vpl#115]
> 1) provider_testcase::test_table_coverage
> The following tables with user fields must be covered with metadata providers: 
>   - vpl_assigned_variations (userid)
>   - vpl_running_processes (userid)
> 
> /siteroot/privacy/tests/provider_test.php:327
> /siteroot/lib/phpunit/classes/advanced_testcase.php:80
> 
> To re-run:
>  vendor/bin/phpunit "provider_testcase" privacy/tests/provider_test.php

Looks like we need to include more metadata fields in our `get_metadata` function. This is testing in moodle 3.9

**Comment by jcrodriguez-dis** [comment]
Thanks for your early bug report, Kristian.

I know that automated tests are needed to ensure the quality of the software, but some generic tests may need to be more customizable:

- The table vpl_running_processes is temporal. This information is kept no farther than some hours. I will add this table with useless information to pass the test.
- The data of the vpl_assigned_variations has been include in the table instead of using a separate table to improve the report readability. The information vpl_assigned_variations is optional, a one to {0,1} relationship from vpl to vpl_assigned_variations for the related user (the really important information is at the vpl_variations table) . To pass the test, I will revert the information unification.

**Comment by jcrodriguez-dis** [comment]
Resolved
