### ISSUE TITLE
Whitelisting an IP address

### ISSUE THREAD

**Issue by CultVonnegut** [jcrodriguez-dis/moodle-mod_vpl#133]
Hello,
we are having an issue with VPL. VPL is blacklisting the haproxy that serves it. For some reason we don't get to understand. I tried to add the haproxy ip in the ignoreip in fail2ban config file: /etc/fail2ban/jail.conf  but VPL keeps blacklisting, so haproxy can't serve the VPL service.
Is thre any other way to whitelist the IP in VPL?
Thanks

**Comment by jcrodriguez-dis** [comment]
Hello.
No, the anti-DoS system in the VPL execution system does not have a whitelist. If you increase the log level you may know why the VPL system blocks your HAProxy. To avoid the problem you can stop the anti-DoS system by setting fail2ban parameter to 0.
I don't know if it is relevant, but I think that the servers of VPL execution system, due to its architecture, fail if controlled by a load balancer.

Best regards,
Juan Carlos.
