### ISSUE TITLE
More info about security vulnerability

### ISSUE THREAD

**Issue by FeldrinH** [jcrodriguez-dis/moodle-mod_vpl#194]
I would like to know more about the impact of the security vulnerability fixed in VPL 4.2.4. The release notes are fairly vague and looking up CVE-2024-34312 I find that this CVE number is reserved but unused. Where could I find more info about this security vulnerability?

**Comment by jcrodriguez-dis** [comment]
Dear @FeldrinH,

Thank you for your inquiry regarding the security vulnerability fixed in VPL 4.2.4. While I understand your concern and desire for more detailed information, it is not advisable to share specific details publicly for security reasons.

However, I can assure you that if you update your VPL-Jail-System, there is no immediate need to update your Moodle plugin.

We apologize for any inconvenience this may have caused.

Best regards,
Juan Carlos

**Comment by FeldrinH** [comment]
My concern is what if someone has exploited the vulnerability before I updated. Could they have gained access to the host system? Escaped VPL jail? What is the potential damage if someone exploited this before the fix was applied?

**Comment by vincentscode** [comment]
Dear @FeldrinH, since your initial question the CVEs have been published and you can find more details on the vulnerabilities at [CVE-2024-34312](https://www.cve.org/CVERecord?id=CVE-2024-34312) and [CVE-2024-34313](https://www.cve.org/CVERecord?id=CVE-2024-34313)
