### ISSUE TITLE
VPL does not recognize a SSL certificate issued by https://letsencrypt.org/

### ISSUE THREAD

**Issue by rhobincu** [jcrodriguez-dis/moodle-mod_vpl#28]
When configuring an execution server, if the installed certificate for a https connection is issued by Let's Encrypt, the message in the `Check execution servers` page is: `request failed: Peer certificate cannot be authenticated with known CA certificates`

**Comment by jcrodriguez-dis** [comment]
The VPL module uses PHP cURL to do requests to the jail server, it seems that your jail server (or cURL) don't have the CA certificate. VPL can bypass this problem by setting the plugin configuration option "Accept self signed certificates".
Please, tell me if this tip resolves the problem.
![captura](https://cloud.githubusercontent.com/assets/2072039/19285990/71f0dd46-8ffc-11e6-89cb-763eed44810b.PNG)

**Comment by rhobincu** [comment]
Hello and thanks for the quick reply. I personally don't have access to the Moodle administration page and although I could e-mail the administrator and ask him to perform this change, it looks more like a workaround than an actual fix, since the CA certificate is NOT self-signed. I do however have administrative access to the execution server, if there are changes required there.

Is there a way to make the VPL plugin accept certificates from Let's Encrypt? I'm asking because the most likely cause for this behavior is that Let's Encrypt is a rather new certificate authority and not all servers accept them yet.

This is the OK link to my execution server: https://executor.dcae.pub.ro/OK and as you can see, your browser accepts the certificate. 

Thank you,
R.

**Comment by jcrodriguez-dis** [comment]
Hello R.
I think that this is not a high security issue.
Notice this:
- This issue is related to connection between the Moodle server and the execution server.
- The risk is about "man in the middle". I suppose not very possible with machines in the same net (your University).
- The information that goes in this conection is students' code and evaluation results.

I think that the correct solution is to install the "DST Root CA X3" certificate (root CA of "Let's Encrypt") in your Moodle server. You can not do anything in your execution server to resolve the problem, except to install a certificate signed by other CA. 

Best regards.
Juan Carlos
