### ISSUE TITLE
AMD folder missing in v3.3.5

### ISSUE THREAD

**Issue by christianwolters** [jcrodriguez-dis/moodle-mod_vpl#87]
Hello Juan Carlos,

first time reporter but some longer time user here so first off: thank you for this module, thank you for your effort and work on this! I really think it is one of the most valuable additions in the plugin ecosystem!

Regarding this small issue: 

* on my testsystem my code is on branch v3.3.5
* I pulled recent commits and well... the syntax highlighting and editor was missing
* I didn't see it at first but: the whole **amd folder is missing**

For now, I switched to branch 3.4dev and all seems to work. Is this ok or do you recommend another branch?

Best regards
Christian

**Comment by jcrodriguez-dis** [comment]
Hello Cristian,
Sorry for the problems. Notice that the 3.3.5 is still not officially released. The issue was with a backport of a VPL3.4dev patch.

The patch resolves a problem with bad language translates that add codes to internationalization strings with parameters.

The 3.3 series does not use AMD.

Best regards,
Juan Carlos.

**Comment by jcrodriguez-dis** [comment]
The problem is currently resolved.

Best regards,
Juan Carlos.

**Comment by christianwolters** [comment]
> Notice that the 3.3.5 is still not officially released. The issue was with a backport of a VPL3.4dev patch.
> The 3.3 series does not use AMD.

Thank you for the clarification, I wasn't aware of that!

**Comment by jcrodriguez-dis** [comment]
V3.3.5 released
Best regards.
