### ISSUE TITLE
Wish List Item

### ISSUE THREAD

**Issue by charliedaly** [jcrodriguez-dis/moodle-mod_vpl#9]
Hi, this isn't an issue, but I couldn't see any feature request option.

Here is a simple addition which I believe would be very useful. VPL should allow some test cases to be hidden. The idea is that a very simple test case would be hidden. If the student fails that test case, they are not shown the output, but it can be flagged so that the TA can examine the code. 

The reasoning is that it catches any student who simply attempts to tailor the output to match the test cases.

**Comment by jcrodriguez-dis** [comment]
Hello Charlie,
this request is already in the TODO list for a future release.

**Comment by tanczosm** [comment]
Would a simple solution to this be to add a line to the test case configuration to specify that case as hidden?

```
case=Check whatever
hidden=true
output=expected text
```

Then the only thing that would need altering would be vpl_evaluate.cpp in the time being to add a check for the "hidden" tag and alter the TestCase class to include an "isHidden" state variable.  Then just omit output for those specific cases.

**Comment by jcrodriguez-dis** [comment]
Hello tanczonsm,
I am working to develop the v3.3 that will increase the features of the built-in evaluation system. The new version will include the following commands:
* Fail message = Text. The Text is shown when the case fail, instead of the common message.
* Free evaluations = number. Number of evaluations that do not lead to apply a reduction by evaluation.
* Reduction by evaluation = number or percentage. Grade reduction by evaluation after spend the free evaluations.
* Expected exit code = Number. Expected exit code of the execution, if match then the case is considered fulfilled.
* Program to run = Path. Program to run in this case instead of the student program
* Program arguments = Args. Arguments to pass to the program in the current case execution

Comments and suggestions are welcomes.

I think that the "hidden =" option has the drawback of the lack of information to the student about the error.

Best regards,
Juan Carlos Rodríguez.

**Comment by jcrodriguez-dis** [comment]
hello tanczonsm,
the V3.3 resolved this issue. Finally, the options "Free evaluations" and "Reduction by evaluation" has been moved from the default evaluation program to the core of the moodle plugin. This change from the previous aproach allow to give detailed information about the evaluation to the students and teachers and allow to apply the penalty using automatic or manual evaluation.
